# Generated by Django 5.1.6 on 2025-03-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('Pothole', 'Pothole'), ('Lighting', 'Lighting'), ('Fly-tipping', 'Fly-tipping'), ('Blocked Drain', 'Blocked Drain'), ('Graffiti', 'Graffiti'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
